# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Deploy to Heroku
        uses: onekiloparsec/heroku-node-deploy-subfolder@v1.0.4
        with:
          # This will be used for authentication. You can find it in your heroku homepage account settings
          api_key: c8b44640-39c2-4fac-bb17-32271dc2700a
          # Email that you use with heroku
          email: andreas.loyning.vu@gmail.com
          # The appname to use for deploying/updating
          app_name: blooming-eyrie-06462
          # The branch that you would like to deploy to Heroku
          branch: master
          # Set this to true if you don't want to use --force when switching branches
          subfolder: server
